# A4 Ticket Format Layouts and Builders
from ..common import (
    HEX_COLOR_DEFAULTS,
    FIELD_ROWS_SECTION_DEFAULTS,
    PRINTER_LAYOUT_NAME,
    PRINTER_LAYOUT_VERSION,
    clone_layout,
    printer_type_config,
)


def default_field_rows():
    return [
        {
            "id": "row-1",
            "fields": [
                {"id": "row-1-field-1", "label": "Serial No.", "source": "serialNo"},
                {"id": "row-1-field-2", "label": "Vehicle No.", "source": "vehicleNo"},
                {"id": "row-1-field-3", "label": "Gross Weight", "source": "grossWeight"},
            ],
        },
        {
            "id": "row-2",
            "fields": [
                {"id": "row-2-field-1", "label": "Date", "source": "entryDate"},
                {"id": "row-2-field-2", "label": "Material", "source": "material"},
                {"id": "row-2-field-3", "label": "Tare Weight", "source": "tareWeight"},
            ],
        },
        {
            "id": "row-3",
            "fields": [
                {"id": "row-3-field-1", "label": "Time", "source": "entryTime"},
                {"id": "row-3-field-2", "label": "Party / Customer", "source": "customer"},
                {"id": "row-3-field-3", "label": "Net Weight", "source": "netWeight"},
            ],
        },
    ]

def default_printer_elements():
    border = HEX_COLOR_DEFAULTS["pageBorder"]
    heading = HEX_COLOR_DEFAULTS["heading"]
    accent = HEX_COLOR_DEFAULTS["accent"]
    text_color = HEX_COLOR_DEFAULTS["text"]

    return [
        {
            "id": "header-logo-block",
            "kind": "staticText",
            "name": "Header Logo Block",
            "x": 2.0,
            "y": 2.4,
            "w": 10.5,
            "h": 18.0,
            "text": "",
            "fontSize": 12,
            "fontWeight": 800,
            "textColor": text_color,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 0,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "header-company-block",
            "kind": "staticText",
            "name": "Header Company Block",
            "x": 13.5,
            "y": 2.4,
            "w": 58.5,
            "h": 18.0,
            "text": "",
            "fontSize": 12,
            "fontWeight": 800,
            "textColor": text_color,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 0,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "header-right-block",
            "kind": "staticText",
            "name": "Header Right Block",
            "x": 73.0,
            "y": 2.4,
            "w": 25.0,
            "h": 18.0,
            "text": "",
            "fontSize": 12,
            "fontWeight": 800,
            "textColor": text_color,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 0,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "logo",
            "kind": "image",
            "name": "Logo",
            "x": 3.1,
            "y": 4.1,
            "w": 8.3,
            "h": 14.2,
            "imageUrl": "",
            "text": "",
            "fontSize": 16,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "company-name",
            "kind": "staticText",
            "name": "Company Name",
            "x": 14.5,
            "y": 1.97,
            "w": 56.5,
            "h": 6.8,
            "text": "SABANAYAGAM TRAILER WEIGH BRIDGE",
            "fontSize": 29,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "address-line",
            "kind": "staticText",
            "name": "Address Line",
            "x": 14.89,
            "y": 8.16,
            "w": 55.5,
            "h": 3.4,
            "text": "NM Sungam, Pollachi. Cell : 98655 86143",
            "fontSize": 16,
            "fontWeight": 600,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "capacity-badge",
            "kind": "staticText",
            "name": "Capacity Badge",
            "x": 28.52,
            "y": 12.7,
            "w": 28.0,
            "h": 6.4,
            "text": "100 TONS CAPACITY",
            "fontSize": 20,
            "fontWeight": 900,
            "textColor": "#FFFFFF",
            "backgroundColor": heading,
            "borderColor": heading,
            "borderWidth": 1,
            "radius": 4,
            "padding": 2,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "gov-title",
            "kind": "staticText",
            "name": "Government Title",
            "x": 73.95,
            "y": 3.46,
            "w": 23.6,
            "h": 5.0,
            "text": "Government Certified",
            "fontSize": 17,
            "fontWeight": 900,
            "textColor": "#FFFFFF",
            "backgroundColor": heading,
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 4,
            "padding": 2,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "gov-line-1",
            "kind": "staticText",
            "name": "Right Panel Line 1",
            "x": 74.3,
            "y": 9.11,
            "w": 22.4,
            "h": 3.56,
            "text": "SMS / WhatsApp",
            "fontSize": 16,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "gov-line-2",
            "kind": "staticText",
            "name": "Right Panel Line 2",
            "x": 74.3,
            "y": 12.31,
            "w": 22.4,
            "h": 3.56,
            "text": "CCTV Camera",
            "fontSize": 16,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "gov-line-3",
            "kind": "staticText",
            "name": "Right Panel Line 3",
            "x": 74.3,
            "y": 15.68,
            "w": 22.4,
            "h": 3.88,
            "text": "24 Hours Service",
            "fontSize": 16,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "field-serial",
            "kind": "field",
            "name": "Serial Number",
            "x": 2.0,
            "y": 24.0,
            "w": 21.5,
            "h": 6.2,
            "label": "S.No.",
            "source": "serialNo",
            "fontSize": 14,
            "valueFontSize": 14,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-date",
            "kind": "field",
            "name": "Entry Date",
            "x": 23.5,
            "y": 24.0,
            "w": 21.5,
            "h": 6.2,
            "label": "Date",
            "source": "entryDate",
            "fontSize": 14,
            "valueFontSize": 14,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-time",
            "kind": "field",
            "name": "Entry Time",
            "x": 45.0,
            "y": 24.0,
            "w": 22.5,
            "h": 6.2,
            "label": "Time",
            "source": "entryTime",
            "fontSize": 14,
            "valueFontSize": 14,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-vehicle",
            "kind": "field",
            "name": "Vehicle Number",
            "x": 67.5,
            "y": 24.0,
            "w": 30.5,
            "h": 6.2,
            "label": "Vehicle No.",
            "source": "vehicleNo",
            "fontSize": 14,
            "valueFontSize": 13,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-customer",
            "kind": "field",
            "name": "Party",
            "x": 2.0,
            "y": 30.2,
            "w": 43.5,
            "h": 6.2,
            "label": "Party",
            "source": "customer",
            "fontSize": 14,
            "valueFontSize": 13,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-material",
            "kind": "field",
            "name": "Material",
            "x": 45.5,
            "y": 30.2,
            "w": 25.5,
            "h": 6.2,
            "label": "Material",
            "source": "material",
            "fontSize": 14,
            "valueFontSize": 13,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "field-charge",
            "kind": "field",
            "name": "Amount",
            "x": 71.0,
            "y": 30.2,
            "w": 27.0,
            "h": 6.2,
            "label": "Amount Rs.",
            "source": "charges",
            "fontSize": 14,
            "valueFontSize": 13,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "photo-1",
            "kind": "photo",
            "name": "Photo 1",
            "x": 2.0,
            "y": 39.5,
            "w": 46.5,
            "h": 37.5,
            "title": "Camera 1",
            "source": "camera:1",
            "fontSize": 10,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "cover",
        },
        {
            "id": "photo-2",
            "kind": "photo",
            "name": "Photo 2",
            "x": 51.5,
            "y": 39.5,
            "w": 46.5,
            "h": 37.5,
            "title": "Camera 2",
            "source": "camera:2",
            "fontSize": 10,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "cover",
        },
        {
            "id": "weight-1",
            "kind": "weight",
            "name": "1st Weight",
            "x": 2.0,
            "y": 79.6,
            "w": 23.25,
            "h": 12.5,
            "label": "1st Weight",
            "source": "grossWeight",
            "unit": "kg",
            "fontSize": 12,
            "valueFontSize": 26,
            "metaSources": ["grossDate", "grossTime"],
            "metaFontSize": 8,
            "fontWeight": 900,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "weight-2",
            "kind": "weight",
            "name": "2nd Weight",
            "x": 26.25,
            "y": 79.6,
            "w": 23.25,
            "h": 12.5,
            "label": "2nd Weight",
            "source": "tareWeight",
            "unit": "kg",
            "fontSize": 12,
            "valueFontSize": 26,
            "metaSources": ["tareDate", "tareTime"],
            "metaFontSize": 8,
            "fontWeight": 900,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "weight-3",
            "kind": "weight",
            "name": "Net Weight",
            "x": 50.5,
            "y": 79.6,
            "w": 23.25,
            "h": 12.5,
            "label": "Net Weight",
            "source": "netWeight",
            "unit": "kg",
            "fontSize": 12,
            "valueFontSize": 26,
            "fontWeight": 900,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 1,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "signature",
            "kind": "staticText",
            "name": "Signature",
            "x": 74.75,
            "y": 79.6,
            "w": 23.25,
            "h": 12.5,
            "text": "Signature",
            "fontSize": 13,
            "fontWeight": 900,
            "textColor": heading,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 2,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "footer-note-block",
            "kind": "staticText",
            "name": "Footer Note Block",
            "x": 2.0,
            "y": 92.1,
            "w": 58.5,
            "h": 6.0,
            "text": "",
            "fontSize": 10,
            "fontWeight": 800,
            "textColor": text_color,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 0,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "footer-thanks-block",
            "kind": "staticText",
            "name": "Footer Thanks Block",
            "x": 61.5,
            "y": 92.1,
            "w": 36.5,
            "h": 6.0,
            "text": "",
            "fontSize": 10,
            "fontWeight": 800,
            "textColor": text_color,
            "backgroundColor": "transparent",
            "borderColor": border,
            "borderWidth": 1,
            "radius": 0,
            "padding": 0,
            "align": "center",
            "fit": "contain",
        },
        {
            "id": "footer-note",
            "kind": "staticText",
            "name": "Footer Note",
            "x": 3.4,
            "y": 93.2,
            "w": 55.7,
            "h": 3.8,
            "text": "Note : Check the weight before vehicle leaving the platform.",
            "fontSize": 16,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 2,
            "align": "left",
            "fit": "contain",
        },
        {
            "id": "footer-thanks",
            "kind": "staticText",
            "name": "Footer Thanks",
            "x": 62.8,
            "y": 93.2,
            "w": 33.9,
            "h": 4.2,
            "text": "Thank you! Visit Again!",
            "fontSize": 16,
            "fontWeight": 900,
            "textColor": accent,
            "backgroundColor": "transparent",
            "borderColor": "transparent",
            "borderWidth": 0,
            "radius": 0,
            "padding": 2,
            "align": "center",
            "fit": "contain",
        },
    ]


def default_a4_printer_layout():
    config = printer_type_config("a4")
    return {
        "version": PRINTER_LAYOUT_VERSION,
        "printerType": config["key"],
        "page": {
            "widthMm": config["page"]["widthMm"],
            "heightMm": config["page"]["heightMm"],
            "backgroundColor": HEX_COLOR_DEFAULTS["pageBackground"],
            "borderColor": HEX_COLOR_DEFAULTS["pageBorder"],
            "borderWidth": config["page"]["borderWidth"],
        },
        "fieldRowsSettings": FIELD_ROWS_SECTION_DEFAULTS.copy(),
        "fieldRows": default_field_rows(),
        "managedSections": [
            {
                "id": "main-field-rows",
                "name": "Field Rows",
                "x": FIELD_ROWS_SECTION_DEFAULTS["x"],
                "y": FIELD_ROWS_SECTION_DEFAULTS["y"],
                "w": FIELD_ROWS_SECTION_DEFAULTS["w"],
                "rowHeight": FIELD_ROWS_SECTION_DEFAULTS["rowHeight"],
                "baseRows": FIELD_ROWS_SECTION_DEFAULTS["baseRows"],
                "shiftStartY": FIELD_ROWS_SECTION_DEFAULTS["shiftStartY"],
                "rows": default_field_rows(),
            },
        ],
        "elements": default_printer_elements(),
    }




def second_default_a4_printer_layout(logo_image_url=""):
    border = "#3D338F"
    heading = "#2F2A6F"
    banner = "#3D338F"

    def box(
        element_id,
        x,
        y,
        w,
        h,
        *,
        z=1,
        border_width=1,
        radius=0,
        background="transparent",
    ):
        return {
            "id": element_id,
            "kind": "staticText",
            "name": element_id.replace("-", " ").title(),
            "x": x,
            "y": y,
            "w": w,
            "h": h,
            "text": "",
            "fontSize": 10,
            "fontWeight": 800,
            "textColor": heading,
            "backgroundColor": background,
            "borderColor": border,
            "borderWidth": border_width,
            "radius": radius,
            "padding": 0,
            "align": "center",
            "fit": "contain",
            "z": z,
        }

    return {
        "version": PRINTER_LAYOUT_VERSION,
        "printerType": "a4",
        "page": {
            "widthMm": 297.0,
            "heightMm": 210.0,
            "backgroundColor": "#FFFFFF",
            "borderColor": border,
            "borderWidth": 4,
        },
        "fieldRowsSettings": {
            "x": 2.5,
            "y": 13.9,
            "w": 95.0,
            "rowHeight": 5.4,
            "baseRows": 1,
            "shiftStartY": 22.0,
        },
        "fieldRows": [
            {
                "id": "meta-row-1",
                "fields": [
                    {"id": "meta-row-1-field-1", "label": "Sl. No.", "source": "serialNo"},
                    {"id": "meta-row-1-field-2", "label": "Date", "source": "entryDate"},
                    {"id": "meta-row-1-field-3", "label": "Time", "source": "entryTime"},
                ],
            },
        ],
        "managedSections": [
            {
                "id": "meta-fields",
                "name": "Top Fields",
                "groupId": "a4-default-2-info-group",
                "x": 2.5,
                "y": 13.9,
                "w": 95.0,
                "rowHeight": 5.4,
                "baseRows": 1,
                "shiftStartY": 22.0,
                "rows": [
                    {
                        "id": "meta-row-1",
                        "fields": [
                            {"id": "meta-row-1-field-1", "label": "Sl. No.", "source": "serialNo"},
                            {"id": "meta-row-1-field-2", "label": "Date", "source": "entryDate"},
                            {"id": "meta-row-1-field-3", "label": "Time", "source": "entryTime"},
                        ],
                    },
                ],
            },
            {
                "id": "party-fields",
                "name": "Party Details",
                "groupId": "a4-default-2-info-group",
                "x": 2.5,
                "y": 63.8,
                "w": 46.5,
                "rowHeight": 6.9,
                "baseRows": 3,
                "shiftStartY": 80.0,
                "rows": [
                    {
                        "id": "party-row-1",
                        "fields": [
                            {"id": "party-row-1-field-1", "label": "Party Name", "source": "customer"},
                        ],
                    },
                    {
                        "id": "party-row-2",
                        "fields": [
                            {"id": "party-row-2-field-1", "label": "Material", "source": "material"},
                        ],
                    },
                    {
                        "id": "party-row-3",
                        "fields": [
                            {"id": "party-row-3-field-1", "label": "Charge Rs.", "source": "charges"},
                        ],
                    },
                ],
            },
            {
                "id": "vehicle-fields",
                "name": "Vehicle Details",
                "groupId": "a4-default-2-info-group",
                "x": 51.0,
                "y": 63.8,
                "w": 46.5,
                "rowHeight": 6.8,
                "baseRows": 1,
                "shiftStartY": 70.8,
                "rows": [
                    {
                        "id": "vehicle-row-1",
                        "fields": [
                            {"id": "vehicle-row-1-field-1", "label": "Vehicle No.", "source": "vehicleNo"},
                        ],
                    },
                ],
            },
        ],
        "elements": [
            box("header-strip-box", 2.5, 2.0, 95.0, 11.5, z=1),
            {
                "id": "logo-image-2",
                "kind": "image",
                "name": "Logo",
                "x": 3.0,
                "y": 2.6,
                "w": 10.5,
                "h": 9.3,
                "imageUrl": logo_image_url,
                "text": "",
                "fontSize": 14,
                "fontWeight": 800,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "weight-1",
                "kind": "weight",
                "name": "Gross Weight",
                "x": 51.0,
                "y": 70.8,
                "w": 15.5,
                "h": 19.0,
                "label": "Gross Weight",
                "source": "grossWeight",
                "unit": "kg",
                "fontSize": 10,
                "valueFontSize": 24,
                "metaSources": ["grossDate", "grossTime"],
                "metaFontSize": 9,
                "fontWeight": 900,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": border,
                "borderWidth": 1,
                "radius": 0,
                "padding": 1,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "weight-2",
                "kind": "weight",
                "name": "Tare Weight",
                "x": 66.5,
                "y": 70.8,
                "w": 15.5,
                "h": 19.0,
                "label": "Tare Weight",
                "source": "tareWeight",
                "unit": "kg",
                "fontSize": 10,
                "valueFontSize": 24,
                "metaSources": ["tareDate", "tareTime"],
                "metaFontSize": 9,
                "fontWeight": 900,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": border,
                "borderWidth": 1,
                "radius": 0,
                "padding": 1,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "weight-3",
                "kind": "weight",
                "name": "Net Weight",
                "x": 82.0,
                "y": 70.8,
                "w": 15.5,
                "h": 19.0,
                "label": "Net Weight",
                "source": "netWeight",
                "unit": "kg",
                "fontSize": 10,
                "valueFontSize": 24,
                "fontWeight": 900,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": border,
                "borderWidth": 1,
                "radius": 0,
                "padding": 1,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "bottom-left-banner",
                "kind": "staticText",
                "name": "Bottom Left Banner",
                "x": 3.0,
                "y": 90.4,
                "w": 46.0,
                "h": 4.4,
                "text": "60 TONS CAPACITY (24 HOURS SERVICE)",
                "fontSize": 16,
                "fontWeight": 900,
                "textColor": "#FFFFFF",
                "backgroundColor": banner,
                "borderColor": banner,
                "borderWidth": 1,
                "radius": 6,
                "padding": 1,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "bottom-right-banner",
                "kind": "staticText",
                "name": "Bottom Right Banner",
                "x": 51.0,
                "y": 90.4,
                "w": 45.5,
                "h": 4.4,
                "text": "GOVERNMENT CERTIFIED",
                "fontSize": 16,
                "fontWeight": 900,
                "textColor": "#FFFFFF",
                "backgroundColor": banner,
                "borderColor": banner,
                "borderWidth": 1,
                "radius": 6,
                "padding": 1,
                "align": "center",
                "fit": "contain",
                "z": 2,
            },
            {
                "id": "company-name-2",
                "kind": "staticText",
                "name": "Company Name 2",
                "x": 15.0,
                "y": 2.6,
                "w": 80.0,
                "h": 4.9,
                "text": "SRI HARI WEIGH BRIDGE",
                "fontSize": 30,
                "fontWeight": 1000,
                "textColor": banner,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "center",
                "fit": "contain",
                "z": 3,
            },
            {
                "id": "company-address-2",
                "kind": "staticText",
                "name": "Company Address 2",
                "x": 15.0,
                "y": 7.4,
                "w": 80.0,
                "h": 4.8,
                "text": "Sathy road, Kadathurpirivu, Kunnathur pudur (PO), SS Kulam (Via), Coimbatore - 641107  Ph : 96777 93899",
                "fontSize": 13,
                "fontWeight": 700,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "center",
                "fit": "contain",
                "z": 3,
            },
            {
                "id": "photo-left",
                "kind": "photo",
                "name": "Photo Left",
                "x": 3.2,
                "y": 23.0,
                "w": 44.1,
                "h": 39.0,
                "title": "",
                "source": "camera:1",
                "fontSize": 10,
                "fontWeight": 800,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "center",
                "fit": "cover",
                "z": 2,
            },
            {
                "id": "photo-right",
                "kind": "photo",
                "name": "Photo Right",
                "x": 51.7,
                "y": 23.0,
                "w": 44.1,
                "h": 39.0,
                "title": "",
                "source": "camera:2",
                "fontSize": 10,
                "fontWeight": 800,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "center",
                "fit": "cover",
                "z": 2,
            },
            {
                "id": "footer-note-2",
                "kind": "staticText",
                "name": "Footer Note 2",
                "x": 3.5,
                "y": 95.6,
                "w": 44.5,
                "h": 2.6,
                "text": "Our responsibility ceases once the vehicle leaves the platform",
                "fontSize": 8,
                "fontWeight": 900,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "left",
                "fit": "contain",
                "z": 3,
            },
            {
                "id": "footer-service-2",
                "kind": "staticText",
                "name": "Footer Service 2",
                "x": 51.5,
                "y": 95.6,
                "w": 44.0,
                "h": 2.6,
                "text": "Mfg & Serviced by TRUCK WEIGH SYSTEMS INDIA PVT. LTD.  Cell : 93622 65431",
                "fontSize": 8,
                "fontWeight": 900,
                "textColor": heading,
                "backgroundColor": "transparent",
                "borderColor": "transparent",
                "borderWidth": 0,
                "radius": 0,
                "padding": 0,
                "align": "left",
                "fit": "contain",
                "z": 3,
            },
        ],
    }




def is_outdated_second_default_a4_layout(layout):
    if not isinstance(layout, dict):
        return False

    by_id = {
        item.get("id")
        for item in layout.get("elements", [])
        if isinstance(item, dict) and item.get("id")
    }
    section_names = {
        section.get("name")
        for section in layout.get("managedSections", [])
        if isinstance(section, dict) and section.get("name")
    }
    return {
        "meta-serial",
        "meta-date",
        "meta-time",
        "party-name",
        "material-name",
        "charge-amount",
        "vehicle-number",
    }.issubset(by_id) or "details-box" in by_id or "Party And Vehicle" in section_names


